### ISSUE TITLE
削除すべきファイル

### ISSUE THREAD

**Issue by munepi** [Yasunari/MacTeX-Uninstaller#1]
いま手元でMacTeX 2017を入れたわけでないですけれども、過去のリリースから存在していたファイルたちのうち、以下のファイルも合わせて削除したほうがよいでしょうか？

 * [x] `/etc/path.d/TeX`: これも消したほうが良いかもしれません。
  * [x]  `/Library/PreferencePanes/TexDist.prefPane/`: システム環境設定（System Preferences）の最下段にある（あった）「TeX Distribution環境設定パネル」
* [x] `/usr/texbin`: El Capitanより前のMac OSにおける MacTeX Directory Structure のTeX関連 bin から張っているシンボリックリンク
    * いまは `/Library/TeX/texbin` に変わりましたね。

**Comment by Yasunari15** [comment]
> * `/etc/path.d/TeX`: これも消したほうが良いかもしれません。

`/etc/paths.d/TeX`を`rm`するように反映いたしました。

> * `パスがどこか忘れました`: "TeX Distribution"環境設定パネル

いろいろと調べてみましたが，仰っているのが何を指すのか分かりませんでした。具体的なPATHはこちらで調べますので，もう少し「環境設定パネル」について説明して頂けませんでしょうか。

**Comment by munepi** [comment]
@Yasunari15 さん、

> いろいろと調べてみましたが，仰っているのが何を指すのか分かりませんでした。
> 具体的なPATHはこちらで調べますので，もう少し「環境設定パネル」について説明して頂けませんでしょうか。

思い出しました！

 * `/Library/PreferencePanes/TexDist.prefPane`: システム環境設定（System Preferences）の最下段にある（あった）「TeX Distribution環境設定パネル」

![2018-07-31 1 15 55](https://user-images.githubusercontent.com/583148/43409862-0c4be00c-9460-11e8-9332-4aada4e3bc44.png)

**Comment by munepi** [comment]
以前の `texbin` も入れておきますか？

 * `/usr/texbin`: El Capitanより前のMac OSにおける MacTeX Disrectory Structure のTeX関連 bin から張っているシンボリックリンク
    * いまは `/Library/TeX/texbin` に変わりましたね。

**Comment by Yasunari15** [comment]
> * `/usr/texbin`: El Capitanより前のMac OSにおける MacTeX Disrectory Structure のTeX関連 bin から張っているシンボリックリンク

MacTeX-2018に対応していると明記している以上，直接組み込むのではなくVersionごとにBranchを作るというのでは，いかがでしょうか。

> * `/Library/PreferencePanes/TexDist.prefPane/`: システム環境設定（System Preferences）の最下段にある（あった）「TeX Distribution環境設定パネル」

こちらも同様ですが，これはMacTeX-2018にもあるものでしょうか。`sudo tlmgr update --self --all`でTerminalからUpdateしているので，GUIがあったことを覚えていませんでした。

ApplicationのPreferencesは消さないようにしてありますが，お好みに合っていますでしょうか。READMEにも記しました通り，実際にはTeXを辞めようと思う人が使ったとしても，本来はmacOSの美学に基づいた方に利用して頂きたいという思いからです。

**Comment by munepi** [comment]
@Yasunari15 さん、

> MacTeX Uninstaller be suppose to work on MacTeX-2018.

おっと、これはうっかり見逃しておりました。

issueタイトルが「削除すべきファイル」というキツイ目なタイトルとしてしまいました（すみません）けれども、よしださんのアプリケーションなので、よしださんのお考え（好みも含めて）でエイっと取捨なさってよいです、はい！

### TexDist.prefPane 

> こちらも同様ですが，これはMacTeX-2018にもあるものでしょうか。

どうやら、MacTeX公式サイトにある [** Multiple TeX Distributions **](http://www.tug.org/mactex/multipletexdistributions.html) の Selecting the Active Distribution によると、このパネルは MacTeX 2017まで存在して、MacTeX 2018 では無くしたようですね（事実上、この機能相当を移行した）。

過去のMacTeXも含めて完全に消すのであれば、TexDist.prefPaneも消しても良いかもしれませんね。

**Comment by Yasunari15** [comment]
こんばんは😴

自分の中でも考えた結果，

* 最新版MacTeXにのみ対応する。
* macOSへの美学をSupportする。

という方針のもと現状維持することに致します。つまり，未来の「過去のMacTeX対応版が欲しい人」のためにも，1年に1回はReleaseすることが必要になりました。

MacTeX-2018が，macOSらしくない場所に撒き散らしたものをご発見されたら，「削除すべきファイル」として，いつでもご連絡ください。

大御所でいらっしゃるmunepi氏と議論させて頂いて，とても貴重な勉強になりました。TeXConfなどでお会いできると嬉しいです。今後とも，よろしくお願い致します。
